/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace Datos {
  export type OrdenStruct = {
    idOrden: PromiseOrValue<BytesLike>;
    siguienteOrdenActiva: PromiseOrValue<BytesLike>;
    anteriorOrdenActiva: PromiseOrValue<BytesLike>;
    siguienteOrdenGemela: PromiseOrValue<BytesLike>;
    anteriorOrdenGemela: PromiseOrValue<BytesLike>;
    vendedor: PromiseOrValue<string>;
    comprador: PromiseOrValue<string>;
    montoVenta: PromiseOrValue<BigNumberish>;
    montoCompra: PromiseOrValue<BigNumberish>;
    fechaCreacion: PromiseOrValue<BigNumberish>;
    fechaFinalizacion: PromiseOrValue<BigNumberish>;
    estado: PromiseOrValue<BigNumberish>;
    tipo: PromiseOrValue<BigNumberish>;
    existe: PromiseOrValue<boolean>;
    tokenCompra: PromiseOrValue<string>;
    tokenVenta: PromiseOrValue<string>;
  };

  export type OrdenStructOutput = [
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    number,
    boolean,
    string,
    string
  ] & {
    idOrden: string;
    siguienteOrdenActiva: string;
    anteriorOrdenActiva: string;
    siguienteOrdenGemela: string;
    anteriorOrdenGemela: string;
    vendedor: string;
    comprador: string;
    montoVenta: BigNumber;
    montoCompra: BigNumber;
    fechaCreacion: BigNumber;
    fechaFinalizacion: BigNumber;
    estado: number;
    tipo: number;
    existe: boolean;
    tokenCompra: string;
    tokenVenta: string;
  };

  export type BilleteraStruct = {
    direccion: PromiseOrValue<string>;
    indiceAdmin: PromiseOrValue<BigNumberish>;
    indiceBloqueado: PromiseOrValue<BigNumberish>;
    rol: PromiseOrValue<BigNumberish>;
    estado: PromiseOrValue<BigNumberish>;
    existe: PromiseOrValue<boolean>;
    ordenes: PromiseOrValue<string>[];
  };

  export type BilleteraStructOutput = [
    string,
    BigNumber,
    BigNumber,
    number,
    number,
    boolean,
    string[]
  ] & {
    direccion: string;
    indiceAdmin: BigNumber;
    indiceBloqueado: BigNumber;
    rol: number;
    estado: number;
    existe: boolean;
    ordenes: string[];
  };

  export type TokenStruct = {
    ticker: PromiseOrValue<string>;
    contrato: PromiseOrValue<string>;
    oraculo: PromiseOrValue<string>;
    decimales: PromiseOrValue<BigNumberish>;
    estado: PromiseOrValue<BigNumberish>;
    existe: PromiseOrValue<boolean>;
  };

  export type TokenStructOutput = [
    string,
    string,
    string,
    number,
    number,
    boolean
  ] & {
    ticker: string;
    contrato: string;
    oraculo: string;
    decimales: number;
    estado: number;
    existe: boolean;
  };
}

export interface DatosInterface extends utils.Interface {
  functions: {
    "emptyString(string)": FunctionFragment;
    "expBySquaring(int256,int256)": FunctionFragment;
    "ordenes()": FunctionFragment;
    "plataforma()": FunctionFragment;
    "safeMulExp(int256,int256)": FunctionFragment;
    "tokensRegistrados(string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "emptyString"
      | "expBySquaring"
      | "ordenes"
      | "plataforma"
      | "safeMulExp"
      | "tokensRegistrados"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "emptyString",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "expBySquaring",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "ordenes", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "plataforma",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeMulExp",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "tokensRegistrados",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "emptyString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expBySquaring",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ordenes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "plataforma", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "safeMulExp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokensRegistrados",
    data: BytesLike
  ): Result;

  events: {
    "NuevaOrden(tuple)": EventFragment;
    "NuevoAdministrador(tuple)": EventFragment;
    "NuevoToken(tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NuevaOrden"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NuevoAdministrador"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NuevoToken"): EventFragment;
}

export interface NuevaOrdenEventObject {
  respuesta: Datos.OrdenStructOutput;
}
export type NuevaOrdenEvent = TypedEvent<
  [Datos.OrdenStructOutput],
  NuevaOrdenEventObject
>;

export type NuevaOrdenEventFilter = TypedEventFilter<NuevaOrdenEvent>;

export interface NuevoAdministradorEventObject {
  respuesta: Datos.BilleteraStructOutput;
}
export type NuevoAdministradorEvent = TypedEvent<
  [Datos.BilleteraStructOutput],
  NuevoAdministradorEventObject
>;

export type NuevoAdministradorEventFilter =
  TypedEventFilter<NuevoAdministradorEvent>;

export interface NuevoTokenEventObject {
  respuesta: Datos.TokenStructOutput;
}
export type NuevoTokenEvent = TypedEvent<
  [Datos.TokenStructOutput],
  NuevoTokenEventObject
>;

export type NuevoTokenEventFilter = TypedEventFilter<NuevoTokenEvent>;

export interface Datos extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DatosInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    emptyString(
      _string: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    expBySquaring(
      number: PromiseOrValue<BigNumberish>,
      exponent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    ordenes(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string] & {
        cantidadTotal: BigNumber;
        cantidadActivas: BigNumber;
        ultimaOrdenActiva: string;
      }
    >;

    plataforma(
      overrides?: CallOverrides
    ): Promise<
      [number, string, BigNumber] & {
        estado: number;
        propietario: string;
        montoMinimoUSD: BigNumber;
      }
    >;

    safeMulExp(
      number: PromiseOrValue<BigNumberish>,
      exponent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokensRegistrados(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, number, number, boolean] & {
        ticker: string;
        contrato: string;
        oraculo: string;
        decimales: number;
        estado: number;
        existe: boolean;
      }
    >;
  };

  emptyString(
    _string: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  expBySquaring(
    number: PromiseOrValue<BigNumberish>,
    exponent: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  ordenes(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, string] & {
      cantidadTotal: BigNumber;
      cantidadActivas: BigNumber;
      ultimaOrdenActiva: string;
    }
  >;

  plataforma(
    overrides?: CallOverrides
  ): Promise<
    [number, string, BigNumber] & {
      estado: number;
      propietario: string;
      montoMinimoUSD: BigNumber;
    }
  >;

  safeMulExp(
    number: PromiseOrValue<BigNumberish>,
    exponent: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokensRegistrados(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, number, number, boolean] & {
      ticker: string;
      contrato: string;
      oraculo: string;
      decimales: number;
      estado: number;
      existe: boolean;
    }
  >;

  callStatic: {
    emptyString(
      _string: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    expBySquaring(
      number: PromiseOrValue<BigNumberish>,
      exponent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ordenes(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string] & {
        cantidadTotal: BigNumber;
        cantidadActivas: BigNumber;
        ultimaOrdenActiva: string;
      }
    >;

    plataforma(
      overrides?: CallOverrides
    ): Promise<
      [number, string, BigNumber] & {
        estado: number;
        propietario: string;
        montoMinimoUSD: BigNumber;
      }
    >;

    safeMulExp(
      number: PromiseOrValue<BigNumberish>,
      exponent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokensRegistrados(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, number, number, boolean] & {
        ticker: string;
        contrato: string;
        oraculo: string;
        decimales: number;
        estado: number;
        existe: boolean;
      }
    >;
  };

  filters: {
    "NuevaOrden(tuple)"(respuesta?: null): NuevaOrdenEventFilter;
    NuevaOrden(respuesta?: null): NuevaOrdenEventFilter;

    "NuevoAdministrador(tuple)"(
      respuesta?: null
    ): NuevoAdministradorEventFilter;
    NuevoAdministrador(respuesta?: null): NuevoAdministradorEventFilter;

    "NuevoToken(tuple)"(respuesta?: null): NuevoTokenEventFilter;
    NuevoToken(respuesta?: null): NuevoTokenEventFilter;
  };

  estimateGas: {
    emptyString(
      _string: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    expBySquaring(
      number: PromiseOrValue<BigNumberish>,
      exponent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ordenes(overrides?: CallOverrides): Promise<BigNumber>;

    plataforma(overrides?: CallOverrides): Promise<BigNumber>;

    safeMulExp(
      number: PromiseOrValue<BigNumberish>,
      exponent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokensRegistrados(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    emptyString(
      _string: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    expBySquaring(
      number: PromiseOrValue<BigNumberish>,
      exponent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ordenes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    plataforma(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    safeMulExp(
      number: PromiseOrValue<BigNumberish>,
      exponent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokensRegistrados(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
