/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testSol from "./Test.sol";
export type { testSol };
export type { Datos } from "./Datos";
export type { GestorTokens } from "./GestorTokens";
export type { Plataforma } from "./Plataforma";
