/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as testSol from "./Test.sol";
export { Datos__factory } from "./Datos__factory";
export { GestorTokens__factory } from "./GestorTokens__factory";
export { Plataforma__factory } from "./Plataforma__factory";
