/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  BigNumberish,
  Overrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { Plataforma, PlataformaInterface } from "../Plataforma";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_test",
        type: "uint8",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [],
    name: "AccesoExitoso",
    type: "event",
  },
  {
    inputs: [],
    name: "prueba",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161019538038061019583398101604081905261002f91610060565b600080546001600160a81b0319163360ff60a01b191617600160a01b60ff939093169290920291909117905561008a565b60006020828403121561007257600080fd5b815160ff8116811461008357600080fd5b9392505050565b60fd806100986000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80637cb5946d14602d575b600080fd5b60336035565b005b6000546001600160a01b03163314609c5760405162461bcd60e51b815260206004820152602160248201527f536f6c6f20656c2070726f706965746172696f207075656465206163636564656044820152603960f91b606482015260840160405180910390fd5b6040517fb6719c462c3db96cfc7ab27c66ec69802d2b81933f5843c7dbfb02ceca167ee590600090a156fea26469706673582212207bbb1323c86577404855820b726bd2cee77fecfd11d94f66d35aa4c57b77482064736f6c63430008110033";

type PlataformaConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PlataformaConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Plataforma__factory extends ContractFactory {
  constructor(...args: PlataformaConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _test: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Plataforma> {
    return super.deploy(_test, overrides || {}) as Promise<Plataforma>;
  }
  override getDeployTransaction(
    _test: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_test, overrides || {});
  }
  override attach(address: string): Plataforma {
    return super.attach(address) as Plataforma;
  }
  override connect(signer: Signer): Plataforma__factory {
    return super.connect(signer) as Plataforma__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PlataformaInterface {
    return new utils.Interface(_abi) as PlataformaInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Plataforma {
    return new Contract(address, _abi, signerOrProvider) as Plataforma;
  }
}
