/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Datos, DatosInterface } from "../../contracts/Datos";

const _abi = [
  {
    inputs: [],
    name: "archivoOrdenes",
    outputs: [
      {
        internalType: "Datos.ContadorOrdenes",
        name: "cantidadTotal",
        type: "uint256",
      },
      {
        internalType: "Datos.ContadorOrdenes",
        name: "cantidadActivas",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "ultimaOrdenActiva",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_string",
        type: "string",
      },
    ],
    name: "emptyString",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "plataforma",
    outputs: [
      {
        internalType: "enum Datos.EstadoGeneral",
        name: "estado",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "propietario",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "montoMinimoUSD",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    name: "tokensMap",
    outputs: [
      {
        internalType: "string",
        name: "ticker",
        type: "string",
      },
      {
        internalType: "address",
        name: "contrato",
        type: "address",
      },
      {
        internalType: "address",
        name: "oraculo",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "decimales",
        type: "uint8",
      },
      {
        internalType: "enum Datos.EstadoGeneral",
        name: "estado",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "existe",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class Datos__factory {
  static readonly abi = _abi;
  static createInterface(): DatosInterface {
    return new utils.Interface(_abi) as DatosInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Datos {
    return new Contract(address, _abi, signerOrProvider) as Datos;
  }
}
