/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Datos, DatosInterface } from "../../contracts/Datos";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "idOrden",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "siguienteOrdenActiva",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "anteriorOrdenActiva",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "siguienteOrdenGemela",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "anteriorOrdenGemela",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "vendedor",
            type: "address",
          },
          {
            internalType: "address",
            name: "comprador",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "montoVenta",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "montoCompra",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "fechaCreacion",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "fechaFinalizacion",
            type: "uint256",
          },
          {
            internalType: "enum Datos.EstadoOrden",
            name: "estado",
            type: "uint8",
          },
          {
            internalType: "enum Datos.TipoOrden",
            name: "tipo",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "existe",
            type: "bool",
          },
          {
            internalType: "string",
            name: "tokenCompra",
            type: "string",
          },
          {
            internalType: "string",
            name: "tokenVenta",
            type: "string",
          },
        ],
        indexed: false,
        internalType: "struct Datos.Orden",
        name: "respuesta",
        type: "tuple",
      },
    ],
    name: "NuevaOrden",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "direccion",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "indiceAdmin",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "indiceBloqueado",
            type: "uint256",
          },
          {
            internalType: "enum Datos.RolBilletera",
            name: "rol",
            type: "uint8",
          },
          {
            internalType: "enum Datos.EstadoGeneral",
            name: "estado",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "existe",
            type: "bool",
          },
          {
            internalType: "string[]",
            name: "ordenes",
            type: "string[]",
          },
        ],
        indexed: false,
        internalType: "struct Datos.Billetera",
        name: "respuesta",
        type: "tuple",
      },
    ],
    name: "NuevoAdministrador",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "ticker",
            type: "string",
          },
          {
            internalType: "address",
            name: "contrato",
            type: "address",
          },
          {
            internalType: "address",
            name: "oraculo",
            type: "address",
          },
          {
            internalType: "uint8",
            name: "decimales",
            type: "uint8",
          },
          {
            internalType: "enum Datos.EstadoGeneral",
            name: "estado",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "existe",
            type: "bool",
          },
        ],
        indexed: false,
        internalType: "struct Datos.Token",
        name: "respuesta",
        type: "tuple",
      },
    ],
    name: "NuevoToken",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_string",
        type: "string",
      },
    ],
    name: "emptyString",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "ordenes",
    outputs: [
      {
        internalType: "uint256",
        name: "cantidadTotal",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "cantidadActivas",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "ultimaOrdenActiva",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "plataforma",
    outputs: [
      {
        internalType: "enum Datos.EstadoGeneral",
        name: "estado",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "propietario",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "montoMinimoUSD",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    name: "tokensRegistrados",
    outputs: [
      {
        internalType: "string",
        name: "ticker",
        type: "string",
      },
      {
        internalType: "address",
        name: "contrato",
        type: "address",
      },
      {
        internalType: "address",
        name: "oraculo",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "decimales",
        type: "uint8",
      },
      {
        internalType: "enum Datos.EstadoGeneral",
        name: "estado",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "existe",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class Datos__factory {
  static readonly abi = _abi;
  static createInterface(): DatosInterface {
    return new utils.Interface(_abi) as DatosInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Datos {
    return new Contract(address, _abi, signerOrProvider) as Datos;
  }
}
