/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Datos__factory } from "./Datos__factory";
export { ERC20Mock__factory } from "./ERC20Mock__factory";
export { GestorTokens__factory } from "./GestorTokens__factory";
export { Plataforma__factory } from "./Plataforma__factory";
