/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AggregatorV3Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AggregatorV3Interface__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "Datos",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Datos__factory>;
    getContractFactory(
      name: "GestorTokens",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GestorTokens__factory>;
    getContractFactory(
      name: "Plataforma",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Plataforma__factory>;
    getContractFactory(
      name: "Pruebas",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pruebas__factory>;

    getContractAt(
      name: "AggregatorV3Interface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AggregatorV3Interface>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "Datos",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Datos>;
    getContractAt(
      name: "GestorTokens",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GestorTokens>;
    getContractAt(
      name: "Plataforma",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Plataforma>;
    getContractAt(
      name: "Pruebas",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Pruebas>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
