/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chainlink from "./@chainlink";
export type { chainlink };
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { AggregatorV3Interface } from "./@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface";
export { AggregatorV3Interface__factory } from "./factories/@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface__factory";
export type { ERC20 } from "./@openzeppelin/contracts/token/ERC20/ERC20";
export { ERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/ERC20__factory";
export type { IERC20Metadata } from "./@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata";
export { IERC20Metadata__factory } from "./factories/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata__factory";
export type { IERC20 } from "./@openzeppelin/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory";
export type { Datos } from "./contracts/Datos";
export { Datos__factory } from "./factories/contracts/Datos__factory";
export type { ERC20Mock } from "./contracts/ERC20Mock";
export { ERC20Mock__factory } from "./factories/contracts/ERC20Mock__factory";
export type { GestorTokens } from "./contracts/GestorTokens";
export { GestorTokens__factory } from "./factories/contracts/GestorTokens__factory";
export type { Plataforma } from "./contracts/Plataforma";
export { Plataforma__factory } from "./factories/contracts/Plataforma__factory";
