/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface PlataformaInterface extends utils.Interface {
  functions: {
    "prueba()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "prueba"): FunctionFragment;

  encodeFunctionData(functionFragment: "prueba", values?: undefined): string;

  decodeFunctionResult(functionFragment: "prueba", data: BytesLike): Result;

  events: {
    "AccesoExitoso()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AccesoExitoso"): EventFragment;
}

export interface AccesoExitosoEventObject {}
export type AccesoExitosoEvent = TypedEvent<[], AccesoExitosoEventObject>;

export type AccesoExitosoEventFilter = TypedEventFilter<AccesoExitosoEvent>;

export interface Plataforma extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PlataformaInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    prueba(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  prueba(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    prueba(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AccesoExitoso()"(): AccesoExitosoEventFilter;
    AccesoExitoso(): AccesoExitosoEventFilter;
  };

  estimateGas: {
    prueba(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    prueba(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
